# Generated by Django 2.1.7 on 2019-09-05 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refuser', models.CharField(default=None, max_length=10)),
                ('mob_no_log', models.CharField(default=None, max_length=10)),
                ('email_log', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='aio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='ar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='bat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='college',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='college_reg_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='cs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='dept',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='food_pref',
            field=models.CharField(blank=True, default='ND', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='mob_no',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='mod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='payment_stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='pp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='pubg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='syt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='th',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='tq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='ty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
